# Generated by Django 4.1 on 2022-08-23 07:23

from django.db import migrations, models
import django.db.models.deletion
import hello.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='new', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='task', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, validators=[hello.validators.MaxLengValidator(100)], verbose_name='zagolovok')),
                ('description', models.TextField(max_length=1000, validators=[hello.validators.MinLengValidator(50)], verbose_name='opisanie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vremy sozdaniy')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='vremy izmeneniy')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracker_status', to='hello.status')),
                ('tracker_type', models.ManyToManyField(blank=True, related_name='trackers', to='hello.type')),
            ],
        ),
    ]
